### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by ai** [seaneking/postcss-clearfix#19]
Having a ChangeLog is a PostCSS rule.

**Comment by TrySound** [comment]
By the way. The last chunk for 1.0.0 :)

**Comment by ai** [comment]
@seaneking you made a major update without ChangeLog? How user will update your plugin and be sure that everything is fine?

**Comment by ai** [comment]
ChangeLog is part of PostCSS Plugin Guidelines: [Rule 4.3](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#43-maintain-a-changelog).

**Comment by seaneking** [comment]
I was happy to leave it at 0.x, as I still consider this plugin in early development. But yep sure, I'll add a changelog if I get around to it, or would welcome a PR.

**Comment by seaneking** [comment]
Fixed in https://github.com/seaneking/postcss-clearfix/commit/f1a0b5ec9680323764940403a7f787db1ed3f8d3
