### ISSUE TITLE
Removes other clear properties

### ISSUE THREAD

**Issue by mikestreety** [seaneking/postcss-clearfix#22]
Hello!

I've just upgraded to `v2` and it seems to be removing other clear properties (e.g. `clear: both`).

I downgraded back to `v1.0.0` and all was restored.

**Comment by mikestreety** [comment]
It appears this line just removes it regardless of what the value was:

https://github.com/seaneking/postcss-clearfix/blob/master/index.js#L46

**Comment by seaneking** [comment]
Wowzers, hell of a regression. Tests should have picked that up, sorry.

I'm away from my computer atm but adding a conditional at the top of the clearFix method that bails if the decl value doesn't === fix should sort it, if you want to submit a PR.

**Comment by mikestreety** [comment]
Ha! I've just realised you're the same author as the other plugin I raised an issue for. You must hate me right now 😉

I'm pretty slammed at the moment, but when I get a second I'll try and get round to it :)

**Comment by seaneking** [comment]
Haha not at all! Thanks for flagging :-) As you can tell these plugins need some love. Trying to make time to maintain my OSS stuff better... 

Will push a patch for this one tonight - should be a v. quick fix.

**Comment by seaneking** [comment]
Fixed in https://github.com/seaneking/postcss-clearfix/commit/22e796e999804fbc4924512a0dceae08ae92dbf2
