### ISSUE TITLE
Clone instead of creating new nodes

### ISSUE THREAD

**Issue by ai** [seaneking/postcss-clearfix#7]
Right no you have a code:

```js
postcss.rule({
  selector: bothRuleSelectors
});
```

It is very bad way:

1. New node has no `source`, so source map will be broken.
2. It produce versions conflict. Right now your plugin uses `postcss 4.x`, so here you will create instace by old class. But plugin can use with PostCSS 5.0. As result AST will have nodes from different versions of PostCSS.

@seaneking it is very big issue, can you fix it today?

**Comment by ai** [comment]
Just use `originNode.clone({ selector: newSelector })`.

**Comment by seaneking** [comment]
Ah, sorry. Built this plugin back when I didn't really know PostCSS too well. Yep will get onto this today.
